package com.fittech.aigymplanner.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val appName: String = "AI Gym Planner",
    val home: String = "Home",
    val log: String = "Log",
    val stats: String = "Stats",
    val profile: String = "Profile",
    val settings: String = "Settings",
    val readyToTrain: String = "Ready to train?",
    val streak: String = "Streak",
    val selectLevel: String = "SELECT LEVEL",
    val yourStats: String = "YOUR STATS",
    val daysWeek: String = "Days/week",
    val exercises: String = "Exercises",
    val saved: String = "Saved",
    val calories: String = "Calories",
    val explore: String = "EXPLORE",
    val exerciseLibrary: String = "Exercise Library",
    val workoutPlan: String = "Workout Plan",
    val workoutHistory: String = "Workout History",
    val smartDashboard: String = "Smart Dashboard",
    val signOut: String = "Sign Out",
    
    // Detailed Strings
    val walking: String = "Walking",
    val running: String = "Running",
    val duration: String = "Duration",
    val minsShort: String = "m",
    val hoursShort: String = "h",
    val totalTrackedTime: String = "TOTAL TRACKED TIME",
    val activityHistory: String = "ACTIVITY HISTORY",
    val smartActivity: String = "SMART ACTIVITY",
    val noWorkouts: String = "No workouts on this day",
    val noSmartActivity: String = "No smart activity on this day",
    val addWorkout: String = "Add Workout",
    val editWorkout: String = "Edit Workout",
    val exerciseName: String = "Exercise Name",
    val sets: String = "Sets",
    val reps: String = "Reps",
    val cancel: String = "Cancel",
    val save: String = "Save",
    val update: String = "Update",
    val add: String = "Add",
    val searchExercises: String = "Search exercises...",
    val noExercisesFound: String = "No exercises found",
    val exerciseCountSuffix: String = "exercise(s)",
    val savedExercises: String = "Saved Exercises",
    val program: String = "Programme",
    val trainingDaysPerWeek: String = "training days per week",
    val day: String = "Day",
    val noExercisesForDay: String = "No exercises for this day.",
    
    // Levels
    val beginner: String = "Beginner",
    val intermediate: String = "Intermediate",
    val advanced: String = "Advanced",
    
    // Settings specific
    val appearance: String = "APPEARANCE",
    val language: String = "LANGUAGE",
    val preferences: String = "PREFERENCES",
    val notifications: String = "Push notifications",
    val workoutReminders: String = "Workout reminders",
    val autoDetect: String = "Auto-detect activity",
    val cloudSync: String = "Cloud sync",
    val syncWithFirebase: String = "Sync with Firebase",
    
    // Auth specific
    val signIn: String = "Sign In",
    val createAccount: String = "Create Account",
    val emailAddress: String = "Email address",
    val password: String = "Password",
    val forgotPassword: String = "Forgot password?",
    val orContinueWith: String = "or continue with",
    val continueWithGoogle: String = "Continue with Google",
    val newHere: String = "New here? Create an account",
    val alreadyHaveAccount: String = "Already have account? Sign In",
    val resetPassword: String = "Reset Password",
    val enterEmailForReset: String = "Enter your email to receive a reset link",
    val sendResetLink: String = "Send Reset Link",
    val fitnessCoach: String = "Your personal fitness coach",
    val joinCommunity: String = "Join our fitness community",
    
    // Greetings
    val goodMorning: String = "Good morning",
    val goodAfternoon: String = "Good afternoon",
    val goodEvening: String = "Good evening"
)

val EnStrings = AppStrings()

val UzStrings = AppStrings(
    home = "Asosiy",
    log = "Tarix",
    stats = "Statistika",
    profile = "Profil",
    settings = "Sozlamalar",
    readyToTrain = "Mashg'ulotga tayyormisiz?",
    streak = "Davomiylik",
    selectLevel = "DARAJANI TANLANG",
    yourStats = "SIZNING STATISTIKANGIZ",
    daysWeek = "Kun/hafta",
    exercises = "Mashqlar",
    saved = "Saqlanganlar",
    calories = "Kaloriya",
    explore = "O'RGANISH",
    exerciseLibrary = "Mashqlar kutubxonasi",
    workoutPlan = "Mashg'ulot rejasi",
    workoutHistory = "Mashg'ulotlar tarixi",
    smartDashboard = "Aqlli panel",
    signOut = "Chiqish",
    walking = "Yurish",
    running = "Yugurish",
    duration = "Davomiyligi",
    minsShort = "daq",
    hoursShort = "s",
    totalTrackedTime = "UMUMIY KUZATILGAN VAQT",
    activityHistory = "FAOLIYAT TARIXI",
    smartActivity = "AQLLI FAOLIYAT",
    noWorkouts = "Bu kunda mashg'ulotlar yo'q",
    noSmartActivity = "Bu kunda aqlli faoliyat yo'q",
    addWorkout = "Mashq qo'shish",
    editWorkout = "Tahrirlash",
    exerciseName = "Mashq nomi",
    sets = "Setlar",
    reps = "Takrorlashlar",
    cancel = "Bekor qilish",
    save = "Saqlash",
    update = "Yangilash",
    add = "Qo'shish",
    searchExercises = "Mashqlarni qidirish...",
    noExercisesFound = "Mashqlar topilmadi",
    exerciseCountSuffix = "ta mashq",
    savedExercises = "Saqlangan mashqlar",
    program = "Dasturi",
    trainingDaysPerWeek = "haftalik mashg'ulot kunlari",
    day = "Kun",
    noExercisesForDay = "Bu kun uchun mashqlar yo'q.",
    beginner = "Boshlang'ich",
    intermediate = "O'rta",
    advanced = "Yuqori",
    appearance = "TASHQI KO'RINISH",
    language = "TIL",
    preferences = "SOZLAMALAR",
    notifications = "Push bildirishnomalar",
    workoutReminders = "Mashg'ulot eslatmalari",
    autoDetect = "Avtomatik aniqlash",
    cloudSync = "Bulutli sinxronizatsiya",
    syncWithFirebase = "Firebase bilan sinxronlash",
    signIn = "Kirish",
    createAccount = "Hisob yaratish",
    emailAddress = "Elektron pochta",
    password = "Parol",
    forgotPassword = "Parolni unutdingizmi?",
    orContinueWith = "yoki davom eting",
    continueWithGoogle = "Google orqali davom etish",
    newHere = "Yangi foydalanuvchimisiz? Ro'yxatdan o'ting",
    alreadyHaveAccount = "Hisobingiz bormi? Kirish",
    resetPassword = "Parolni tiklash",
    enterEmailForReset = "Parolni tiklash havolasini olish uchun pochtangizni kiriting",
    sendResetLink = "Tiklash havolasini yuborish",
    fitnessCoach = "Sizning shaxsiy fitnes murabbiyingiz",
    joinCommunity = "Bizning fitnes hamjamiyatimizga qo'shiling",
    goodMorning = "Xayrli tong",
    goodAfternoon = "Xayrli kun",
    goodEvening = "Xayrli kech"
)

val RuStrings = AppStrings(
    home = "Главная",
    log = "История",
    stats = "Статистика",
    profile = "Профиль",
    settings = "Настройки",
    readyToTrain = "Готовы к тренировке?",
    streak = "Серия",
    selectLevel = "ВЫБЕРИТЕ УРОВЕНЬ",
    yourStats = "ВАША СТАТИСТИКА",
    daysWeek = "Дни/нед",
    exercises = "Упражнения",
    saved = "Сохранено",
    calories = "Калории",
    explore = "ОБЗОР",
    exerciseLibrary = "Библиотека упражнений",
    workoutPlan = "План тренировок",
    workoutHistory = "История тренировок",
    smartDashboard = "Умная панель",
    signOut = "Выйти",
    walking = "Ходьба",
    running = "Бег",
    duration = "Длительность",
    minsShort = "м",
    hoursShort = "ч",
    totalTrackedTime = "ОБЩЕЕ ВРЕМЯ",
    activityHistory = "ИСТОРИЯ АКТИВНОСТИ",
    smartActivity = "УМНАЯ АКТИВНОСТЬ",
    noWorkouts = "Нет тренировок в этот день",
    noSmartActivity = "Нет умной активности в этот день",
    addWorkout = "Добавить тренировку",
    editWorkout = "Изменить",
    exerciseName = "Название упражнения",
    sets = "Подходы",
    reps = "Повторения",
    cancel = "Отмена",
    save = "Сохранить",
    update = "Обновить",
    add = "Добавить",
    searchExercises = "Поиск упражнений...",
    noExercisesFound = "Упражнения не найдены",
    exerciseCountSuffix = "упражнение(й)",
    savedExercises = "Сохраненные упражнения",
    program = "Программа",
    trainingDaysPerWeek = "тренировочных дня в неделю",
    day = "День",
    noExercisesForDay = "Нет упражнений на этот день.",
    beginner = "Новичок",
    intermediate = "Средний",
    advanced = "Продвинутый",
    appearance = "ВНЕШНИЙ ВИД",
    language = "ЯЗЫК",
    preferences = "ПРЕДПОЧТЕНИЯ",
    notifications = "Уведомления",
    workoutReminders = "Напоминания о тренировках",
    autoDetect = "Автоопределение активности",
    cloudSync = "Облачная синхронизация",
    syncWithFirebase = "Синхронизация с Firebase",
    signIn = "Войти",
    createAccount = "Создать аккаунт",
    emailAddress = "Электронная почта",
    password = "Пароль",
    forgotPassword = "Забыли пароль?",
    orContinueWith = "или продолжите через",
    continueWithGoogle = "Продолжить через Google",
    newHere = "Впервые здесь? Создайте аккаунт",
    alreadyHaveAccount = "Уже есть аккаунт? Войти",
    resetPassword = "Сброс пароля",
    enterEmailForReset = "Введите email для получения ссылки для сброса",
    sendResetLink = "Отправить ссылку",
    fitnessCoach = "Ваш личный фитнес-тренер",
    joinCommunity = "Присоединяйтесь к нашему сообществу",
    goodMorning = "Доброе утро",
    goodAfternoon = "Добрый день",
    goodEvening = "Добрый вечер"
)

val LocalAppStrings = staticCompositionLocalOf { EnStrings }

@Composable
@ReadOnlyComposable
fun appStrings() = LocalAppStrings.current

fun getAppStrings(language: String): AppStrings {
    return when (language) {
        "uz" -> UzStrings
        "ru" -> RuStrings
        else -> EnStrings
    }
}
